steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-helloworld:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-helloworld:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'flask-helloworld', '--image=gcr.io/$PROJECT_ID/flask-helloworld:$COMMIT_SHA', '--region=asia-east1', '--platform=managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/flask-helloworld:$COMMIT_SHA'
